import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.css";
import PageHeader from "components/PageHeader";
import Container from "components/Container";
import { useGenreList } from "hooks/genre";
import { useMovieList } from "../hooks/movie";
import MoviesGenre from '../components/MoviesGenre'

export default function Home() {
  const genreList = useGenreList();
  const movieList = useMovieList({ genreId: 18 });

  console.log('genreList', genreList.data);
  console.log('movieList', movieList.data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader />
      <Container>
        { genreList?.data?.map(genre => (
          <MoviesGenre key={genre?.id} genreName={genre?.name} genreId={genre?.id}/>
        ))}
      </Container>
    </div>
  );
}
