import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.css";
import PageHeader from "components/PageHeader";
import Container from "components/Container";
import { useGenreList } from "hooks/genre";
import { useMovieList } from "../hooks/movie";

export default function Home() {
  const genreList = useGenreList();
  const movieList = useMovieList({ genreId: 18 });

  console.log('genreList', genreList.data);
  console.log('movieList', movieList.data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader />
      <Container>
        <main style={{ padding: "2em" }}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
          pulvinar lorem et posuere lobortis. Nam vestibulum fringilla orci id
          pellentesque. Donec ultricies risus quis elementum finibus. Maecenas
          sodales dui turpis, a faucibus velit vulputate at. Praesent nec porta
          dui, eu sollicitudin purus. Nullam in urna a est consequat tincidunt
          at vitae dui. Vivamus ac lobortis arcu. Maecenas molestie elit eget
          justo sagittis facilisis. In tempus arcu eget odio aliquet pulvinar.
          Fusce finibus nisl quis nisi tempus, vel faucibus sem maximus.
          Praesent nec lobortis justo, in sodales lectus. Nunc placerat, erat at
          convallis laoreet, velit nisl aliquet velit, at placerat odio ipsum
          sed dui. Duis vel lacinia elit. Integer consequat efficitur erat et
          molestie. Donec euismod ornare aliquam. Praesent in laoreet quam.
          Integer id massa nibh. Integer semper lobortis vulputate. Integer
          tristique nunc non felis iaculis imperdiet. Sed faucibus nisi nec
          lacus congue venenatis. Interdum et malesuada fames ac ante ipsum
          primis in faucibus. Sed tristique varius massa, non vulputate nisl
          porta eget. Nunc egestas orci in enim faucibus tristique eu in nibh.
          Phasellus volutpat pulvinar elit, et laoreet nunc dignissim quis.
          Praesent sit amet mauris consequat, fermentum erat ac, porta purus.
          Proin facilisis metus ut risus faucibus, in fringilla turpis aliquam.
          Etiam vestibulum arcu lobortis, faucibus urna in, molestie diam.
          Phasellus lobortis lectus et mi bibendum, mattis ullamcorper quam
          vulputate. Sed sed leo nec nulla gravida ornare nec quis mi. Nullam ut
          imperdiet tortor, eu fringilla elit. Donec sit amet eros ex. Maecenas
          sollicitudin tortor vel urna vulputate tempus vel at magna. Proin
          elementum elit nibh, id malesuada turpis ornare eget. Sed tellus
          felis, aliquet ut molestie ut, aliquet sed diam. Sed lorem augue,
          tincidunt quis placerat eu, ullamcorper id sapien. Vivamus dignissim
          felis id arcu pellentesque, vitae dapibus erat condimentum. In
          facilisis libero ex, interdum facilisis neque ultricies nec.
          Pellentesque habitant morbi tristique senectus et netus et malesuada
          fames ac turpis egestas. Nunc venenatis ultrices sapien ut gravida.
          Duis congue in nunc nec condimentum. Phasellus eget eros eu nibh
          aliquam efficitur id nec mauris. Sed hendrerit libero vel ultricies
          sagittis. Duis suscipit ex at ligula faucibus, et dapibus mi
          elementum. Orci varius natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus. Nunc eget mollis turpis. Nam auctor
          tortor sed dolor lobortis finibus. Nulla urna sapien, dignissim eget
          lacinia ac, efficitur vitae dolor. Interdum et malesuada fames ac ante
          ipsum primis in faucibus. Sed sed urna odio. Aenean non dignissim
          nibh, sit amet pulvinar elit. Lorem ipsum dolor sit amet, consectetur
          adipiscing elit. Curabitur pulvinar lorem et posuere lobortis. Nam
          vestibulum fringilla orci id pellentesque. Donec ultricies risus quis
          elementum finibus. Maecenas sodales dui turpis, a faucibus velit
          vulputate at. Praesent nec porta dui, eu sollicitudin purus. Nullam in
          urna a est consequat tincidunt at vitae dui. Vivamus ac lobortis arcu.
          Maecenas molestie elit eget justo sagittis facilisis. In tempus arcu
          eget odio aliquet pulvinar. Fusce finibus nisl quis nisi tempus, vel
          faucibus sem maximus. Praesent nec lobortis justo, in sodales lectus.
          Nunc placerat, erat at convallis laoreet, velit nisl aliquet velit, at
          placerat odio ipsum sed dui. Duis vel lacinia elit. Integer consequat
          efficitur erat et molestie. Donec euismod ornare aliquam. Praesent in
          laoreet quam. Integer id massa nibh. Integer semper lobortis
          vulputate. Integer tristique nunc non felis iaculis imperdiet. Sed
          faucibus nisi nec lacus congue venenatis. Interdum et malesuada fames
          ac ante ipsum primis in faucibus. Sed tristique varius massa, non
          vulputate nisl porta eget. Nunc egestas orci in enim faucibus
          tristique eu in nibh. Phasellus volutpat pulvinar elit, et laoreet
          nunc dignissim quis. Praesent sit amet mauris consequat, fermentum
          erat ac, porta purus. Proin facilisis metus ut risus faucibus, in
          fringilla turpis aliquam. Etiam vestibulum arcu lobortis, faucibus
          urna in, molestie diam. Phasellus lobortis lectus et mi bibendum,
          mattis ullamcorper quam vulputate. Sed sed leo nec nulla gravida
          ornare nec quis mi. Nullam ut imperdiet tortor, eu fringilla elit.
          Donec sit amet eros ex. Maecenas sollicitudin tortor vel urna
          vulputate tempus vel at magna. Proin elementum elit nibh, id malesuada
          turpis ornare eget. Sed tellus felis, aliquet ut molestie ut, aliquet
          sed diam. Sed lorem augue, tincidunt quis placerat eu, ullamcorper id
          sapien. Vivamus dignissim felis id arcu pellentesque, vitae dapibus
          erat condimentum. In facilisis libero ex, interdum facilisis neque
          ultricies nec. Pellentesque habitant morbi tristique senectus et netus
          et malesuada fames ac turpis egestas. Nunc venenatis ultrices sapien
          ut gravida. Duis congue in nunc nec condimentum. Phasellus eget eros
          eu nibh aliquam efficitur id nec mauris. Sed hendrerit libero vel
          ultricies sagittis. Duis suscipit ex at ligula faucibus, et dapibus mi
          elementum. Orci varius natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus. Nunc eget mollis turpis. Nam auctor
          tortor sed dolor lobortis finibus. Nulla urna sapien, dignissim eget
          lacinia ac, efficitur vitae dolor. Interdum et malesuada fames ac ante
          ipsum primis in faucibus. Sed sed urna odio. Aenean non dignissim
          nibh, sit amet pulvinar elit. Lorem ipsum dolor sit amet, consectetur
          adipiscing elit. Curabitur pulvinar lorem et posuere lobortis. Nam
          vestibulum fringilla orci id pellentesque. Donec ultricies risus quis
          elementum finibus. Maecenas sodales dui turpis, a faucibus velit
          vulputate at. Praesent nec porta dui, eu sollicitudin purus. Nullam in
          urna a est consequat tincidunt at vitae dui. Vivamus ac lobortis arcu.
          Maecenas molestie elit eget justo sagittis facilisis. In tempus arcu
          eget odio aliquet pulvinar. Fusce finibus nisl quis nisi tempus, vel
          faucibus sem maximus. Praesent nec lobortis justo, in sodales lectus.
          Nunc placerat, erat at convallis laoreet, velit nisl aliquet velit, at
          placerat odio ipsum sed dui. Duis vel lacinia elit. Integer consequat
          efficitur erat et molestie. Donec euismod ornare aliquam. Praesent in
          laoreet quam. Integer id massa nibh. Integer semper lobortis
          vulputate. Integer tristique nunc non felis iaculis imperdiet. Sed
          faucibus nisi nec lacus congue venenatis. Interdum et malesuada fames
          ac ante ipsum primis in faucibus. Sed tristique varius massa, non
          vulputate nisl porta eget. Nunc egestas orci in enim faucibus
          tristique eu in nibh. Phasellus volutpat pulvinar elit, et laoreet
          nunc dignissim quis. Praesent sit amet mauris consequat, fermentum
          erat ac, porta purus. Proin facilisis metus ut risus faucibus, in
          fringilla turpis aliquam. Etiam vestibulum arcu lobortis, faucibus
          urna in, molestie diam. Phasellus lobortis lectus et mi bibendum,
          mattis ullamcorper quam vulputate. Sed sed leo nec nulla gravida
          ornare nec quis mi. Nullam ut imperdiet tortor, eu fringilla elit.
          Donec sit amet eros ex. Maecenas sollicitudin tortor vel urna
          vulputate tempus vel at magna. Proin elementum elit nibh, id malesuada
          turpis ornare eget. Sed tellus felis, aliquet ut molestie ut, aliquet
          sed diam. Sed lorem augue, tincidunt quis placerat eu, ullamcorper id
          sapien. Vivamus dignissim felis id arcu pellentesque, vitae dapibus
          erat condimentum. In facilisis libero ex, interdum facilisis neque
          ultricies nec. Pellentesque habitant morbi tristique senectus et netus
          et malesuada fames ac turpis egestas. Nunc venenatis ultrices sapien
          ut gravida. Duis congue in nunc nec condimentum. Phasellus eget eros
          eu nibh aliquam efficitur id nec mauris. Sed hendrerit libero vel
          ultricies sagittis. Duis suscipit ex at ligula faucibus, et dapibus mi
          elementum. Orci varius natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus. Nunc eget mollis turpis. Nam auctor
          tortor sed dolor lobortis finibus. Nulla urna sapien, dignissim eget
          lacinia ac, efficitur vitae dolor. Interdum et malesuada fames ac ante
          ipsum primis in faucibus. Sed sed urna odio. Aenean non dignissim
          nibh, sit amet pulvinar elit. Lorem ipsum dolor sit amet, consectetur
          adipiscing elit. Curabitur pulvinar lorem et posuere lobortis. Nam
          vestibulum fringilla orci id pellentesque. Donec ultricies risus quis
          elementum finibus. Maecenas sodales dui turpis, a faucibus velit
          vulputate at. Praesent nec porta dui, eu sollicitudin purus. Nullam in
          urna a est consequat tincidunt at vitae dui. Vivamus ac lobortis arcu.
          Maecenas molestie elit eget justo sagittis facilisis. In tempus arcu
          eget odio aliquet pulvinar. Fusce finibus nisl quis nisi tempus, vel
          faucibus sem maximus. Praesent nec lobortis justo, in sodales lectus.
          Nunc placerat, erat at convallis laoreet, velit nisl aliquet velit, at
          placerat odio ipsum sed dui. Duis vel lacinia elit. Integer consequat
          efficitur erat et molestie. Donec euismod ornare aliquam. Praesent in
          laoreet quam. Integer id massa nibh. Integer semper lobortis
          vulputate. Integer tristique nunc non felis iaculis imperdiet. Sed
          faucibus nisi nec lacus congue venenatis. Interdum et malesuada fames
          ac ante ipsum primis in faucibus. Sed tristique varius massa, non
          vulputate nisl porta eget. Nunc egestas orci in enim faucibus
          tristique eu in nibh. Phasellus volutpat pulvinar elit, et laoreet
          nunc dignissim quis. Praesent sit amet mauris consequat, fermentum
          erat ac, porta purus. Proin facilisis metus ut risus faucibus, in
          fringilla turpis aliquam. Etiam vestibulum arcu lobortis, faucibus
          urna in, molestie diam. Phasellus lobortis lectus et mi bibendum,
          mattis ullamcorper quam vulputate. Sed sed leo nec nulla gravida
          ornare nec quis mi. Nullam ut imperdiet tortor, eu fringilla elit.
          Donec sit amet eros ex. Maecenas sollicitudin tortor vel urna
          vulputate tempus vel at magna. Proin elementum elit nibh, id malesuada
          turpis ornare eget. Sed tellus felis, aliquet ut molestie ut, aliquet
          sed diam. Sed lorem augue, tincidunt quis placerat eu, ullamcorper id
          sapien. Vivamus dignissim felis id arcu pellentesque, vitae dapibus
          erat condimentum. In facilisis libero ex, interdum facilisis neque
          ultricies nec. Pellentesque habitant morbi tristique senectus et netus
          et malesuada fames ac turpis egestas. Nunc venenatis ultrices sapien
          ut gravida. Duis congue in nunc nec condimentum. Phasellus eget eros
          eu nibh aliquam efficitur id nec mauris. Sed hendrerit libero vel
          ultricies sagittis. Duis suscipit ex at ligula faucibus, et dapibus mi
          elementum. Orci varius natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus. Nunc eget mollis turpis. Nam auctor
          tortor sed dolor lobortis finibus. Nulla urna sapien, dignissim eget
          lacinia ac, efficitur vitae dolor. Interdum et malesuada fames ac ante
          ipsum primis in faucibus. Sed sed urna odio. Aenean non dignissim
          nibh, sit amet pulvinar elit. Lorem ipsum dolor sit amet, consectetur
          adipiscing elit. Curabitur pulvinar lorem et posuere lobortis. Nam
          vestibulum fringilla orci id pellentesque. Donec ultricies risus quis
          elementum finibus. Maecenas sodales dui turpis, a faucibus velit
          vulputate at. Praesent nec porta dui, eu sollicitudin purus. Nullam in
          urna a est consequat tincidunt at vitae dui. Vivamus ac lobortis arcu.
          Maecenas molestie elit eget justo sagittis facilisis. In tempus arcu
          eget odio aliquet pulvinar. Fusce finibus nisl quis nisi tempus, vel
          faucibus sem maximus. Praesent nec lobortis justo, in sodales lectus.
          Nunc placerat, erat at convallis laoreet, velit nisl aliquet velit, at
          placerat odio ipsum sed dui. Duis vel lacinia elit. Integer consequat
          efficitur erat et molestie. Donec euismod ornare aliquam. Praesent in
          laoreet quam. Integer id massa nibh. Integer semper lobortis
          vulputate. Integer tristique nunc non felis iaculis imperdiet. Sed
          faucibus nisi nec lacus congue venenatis. Interdum et malesuada fames
          ac ante ipsum primis in faucibus. Sed tristique varius massa, non
          vulputate nisl porta eget. Nunc egestas orci in enim faucibus
          tristique eu in nibh. Phasellus volutpat pulvinar elit, et laoreet
          nunc dignissim quis. Praesent sit amet mauris consequat, fermentum
          erat ac, porta purus. Proin facilisis metus ut risus faucibus, in
          fringilla turpis aliquam. Etiam vestibulum arcu lobortis, faucibus
          urna in, molestie diam. Phasellus lobortis lectus et mi bibendum,
          mattis ullamcorper quam vulputate. Sed sed leo nec nulla gravida
          ornare nec quis mi. Nullam ut imperdiet tortor, eu fringilla elit.
          Donec sit amet eros ex. Maecenas sollicitudin tortor vel urna
          vulputate tempus vel at magna. Proin elementum elit nibh, id malesuada
          turpis ornare eget. Sed tellus felis, aliquet ut molestie ut, aliquet
          sed diam. Sed lorem augue, tincidunt quis placerat eu, ullamcorper id
          sapien. Vivamus dignissim felis id arcu pellentesque, vitae dapibus
          erat condimentum. In facilisis libero ex, interdum facilisis neque
          ultricies nec. Pellentesque habitant morbi tristique senectus et netus
          et malesuada fames ac turpis egestas. Nunc venenatis ultrices sapien
          ut gravida. Duis congue in nunc nec condimentum. Phasellus eget eros
          eu nibh aliquam efficitur id nec mauris. Sed hendrerit libero vel
          ultricies sagittis. Duis suscipit ex at ligula faucibus, et dapibus mi
          elementum. Orci varius natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus. Nunc eget mollis turpis. Nam auctor
          tortor sed dolor lobortis finibus. Nulla urna sapien, dignissim eget
          lacinia ac, efficitur vitae dolor. Interdum et malesuada fames ac ante
          ipsum primis in faucibus. Sed sed urna odio. Aenean non dignissim
          nibh, sit amet pulvinar elit. Lorem ipsum dolor sit amet, consectetur
          adipiscing elit. Curabitur pulvinar lorem et posuere lobortis. Nam
          vestibulum fringilla orci id pellentesque. Donec ultricies risus quis
          elementum finibus. Maecenas sodales dui turpis, a faucibus velit
          vulputate at. Praesent nec porta dui, eu sollicitudin purus. Nullam in
          urna a est consequat tincidunt at vitae dui. Vivamus ac lobortis arcu.
          Maecenas molestie elit eget justo sagittis facilisis. In tempus arcu
          eget odio aliquet pulvinar. Fusce finibus nisl quis nisi tempus, vel
          faucibus sem maximus. Praesent nec lobortis justo, in sodales lectus.
          Nunc placerat, erat at convallis laoreet, velit nisl aliquet velit, at
          placerat odio ipsum sed dui. Duis vel lacinia elit. Integer consequat
          efficitur erat et molestie. Donec euismod ornare aliquam. Praesent in
          laoreet quam. Integer id massa nibh. Integer semper lobortis
          vulputate. Integer tristique nunc non felis iaculis imperdiet. Sed
          faucibus nisi nec lacus congue venenatis. Interdum et malesuada fames
          ac ante ipsum primis in faucibus. Sed tristique varius massa, non
          vulputate nisl porta eget. Nunc egestas orci in enim faucibus
          tristique eu in nibh. Phasellus volutpat pulvinar elit, et laoreet
          nunc dignissim quis. Praesent sit amet mauris consequat, fermentum
          erat ac, porta purus. Proin facilisis metus ut risus faucibus, in
          fringilla turpis aliquam. Etiam vestibulum arcu lobortis, faucibus
          urna in, molestie diam. Phasellus lobortis lectus et mi bibendum,
          mattis ullamcorper quam vulputate. Sed sed leo nec nulla gravida
          ornare nec quis mi. Nullam ut imperdiet tortor, eu fringilla elit.
          Donec sit amet eros ex. Maecenas sollicitudin tortor vel urna
          vulputate tempus vel at magna. Proin elementum elit nibh, id malesuada
          turpis ornare eget. Sed tellus felis, aliquet ut molestie ut, aliquet
          sed diam. Sed lorem augue, tincidunt quis placerat eu, ullamcorper id
          sapien. Vivamus dignissim felis id arcu pellentesque, vitae dapibus
          erat condimentum. In facilisis libero ex, interdum facilisis neque
          ultricies nec. Pellentesque habitant morbi tristique senectus et netus
          et malesuada fames ac turpis egestas. Nunc venenatis ultrices sapien
          ut gravida. Duis congue in nunc nec condimentum. Phasellus eget eros
          eu nibh aliquam efficitur id nec mauris. Sed hendrerit libero vel
          ultricies sagittis. Duis suscipit ex at ligula faucibus, et dapibus mi
          elementum. Orci varius natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus. Nunc eget mollis turpis. Nam auctor
          tortor sed dolor lobortis finibus. Nulla urna sapien, dignissim eget
          lacinia ac, efficitur vitae dolor. Interdum et malesuada fames ac ante
          ipsum primis in faucibus. Sed sed urna odio. Aenean non dignissim
          nibh, sit amet pulvinar elit.
        </main>
      </Container>
    </div>
  );
}
